services:
  postgres:
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change-me-in-production}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-change-me-in-production}@postgres:5432/tenflow
      SECRET_KEY: ${SECRET_KEY:-change-me-in-production}
      FRONTEND_URL: ${FRONTEND_URL:-https://yourdomain.com}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    volumes: []  # No volume mounts in production

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # SSL certificates would go here
      # - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend

volumes:
  postgres_data_prod:
