"""add_user_training_plan_relationship

Revision ID: 381b83d50e67
Revises: 148d733d2edf
Create Date: 2025-08-17 15:14:58.542021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381b83d50e67'
down_revision: Union[str, None] = '148d733d2edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'training_plans', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_plans', type_='foreignkey')
    # ### end Alembic commands ###
